version: '3'


services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:9000"
    container_name: ngecommerce
    restart: always
    volumes: 
      - .:/ngecommerce
    ports: 
      - "9000:9000"
    networks:
      - ecommerce_net


networks:
  ecommerce_net:
    driver: bridge